
import { queryOptions as TANSTACK_QUERY_OPTIONS, mutationOptions as TANSTACK_MUTATION_OPTIONS } from "@tanstack/react-query";

// This file was generated by [tauri-specta](https://github.com/specta-rs/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getUser(id: number) : Promise<Result<User, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_user", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listUsers() : Promise<User[]> {
    return await TAURI_INVOKE("list_users");
},
async listTodos(userId: number, title: string | null) : Promise<Todo[]> {
    return await TAURI_INVOKE("list_todos", { userId, title });
},
async createUser(name: string, email: string) : Promise<Result<User, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_user", { name, email }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createTodo(title: string, userId: number) : Promise<Result<Todo, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_todo", { title, userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteUser(id: number) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_user", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTodo(id: number) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_todo", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined query keys **/


export const queryKeys = {
    getUser: (id?: number) => filterKey(["getUser"] as const, { id }),
listUsers: () => ["listUsers"] as const,
listTodos: (userId?: number, title?: string | null) => filterKey(["listTodos"] as const, { userId, title })
}

/** user-defined queries **/


export const queries = {
    getUser: (id: number) => TANSTACK_QUERY_OPTIONS<User, ApiError>({ queryKey: queryKeys.getUser(id), queryFn: () => unwrapTypedError(commands.getUser(id)) }),
listUsers: () => TANSTACK_QUERY_OPTIONS<User[]>({ queryKey: queryKeys.listUsers(), queryFn: () => commands.listUsers() }),
listTodos: (userId: number, title: string | null) => TANSTACK_QUERY_OPTIONS<Todo[]>({ queryKey: queryKeys.listTodos(userId, title), queryFn: () => commands.listTodos(userId, title) })
}

/** user-defined mutation keys **/


export const mutationKeys = {
    createUser: () => ["createUser"] as const,
createTodo: () => ["createTodo"] as const,
deleteUser: () => ["deleteUser"] as const,
deleteTodo: () => ["deleteTodo"] as const
}

/** user-defined mutations **/


export const mutations = {
    createUser: () => TANSTACK_MUTATION_OPTIONS<User, ApiError, { name: string, email: string }>({ mutationKey: mutationKeys.createUser(), mutationFn: ({ name, email }: { name: string, email: string }) => unwrapTypedError(commands.createUser(name, email)) }),
createTodo: () => TANSTACK_MUTATION_OPTIONS<Todo, ApiError, { title: string, userId: number }>({ mutationKey: mutationKeys.createTodo(), mutationFn: ({ title, userId }: { title: string, userId: number }) => unwrapTypedError(commands.createTodo(title, userId)) }),
deleteUser: () => TANSTACK_MUTATION_OPTIONS<null, ApiError, { id: number }>({ mutationKey: mutationKeys.deleteUser(), mutationFn: ({ id }: { id: number }) => unwrapTypedError(commands.deleteUser(id)) }),
deleteTodo: () => TANSTACK_MUTATION_OPTIONS<null, ApiError, { id: number }>({ mutationKey: mutationKeys.deleteTodo(), mutationFn: ({ id }: { id: number }) => unwrapTypedError(commands.deleteTodo(id)) })
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ApiError = { type: "NotFound"; data: string } | { type: "Internal"; data: string }
export type Todo = { id: number; title: string; completed: boolean; user_id: number }
export type User = { id: number; name: string; email: string }

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type Webview as __Webview__ } from "@tauri-apps/api/webview";
import { type Window as __Window__ } from "@tauri-apps/api/window";

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };

export function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>,
) {
  const result = {} as {
    [K in keyof T]: __EventObj__<T[K]> & {
      (window: __Webview__ | __Window__): __EventObj__<T[K]>;
    };
  };

  for (const key in mappings) {
    const name = mappings[key];

    const base: __EventObj__<any> = {
      listen: (cb) => TAURI_API_EVENT.listen(name, cb),
      once: (cb) => TAURI_API_EVENT.once(name, cb),
      emit: (payload: any) => TAURI_API_EVENT.emit(name, payload),
    };

    const withWindow = (
      window: __Webview__ | __Window__,
    ): __EventObj__<any> => ({
      listen: (cb) => window.listen(name, cb),
      once: (cb) => window.once(name, cb),
      emit: (payload: any) => window.emit(name, payload),
    });

    result[key] = Object.assign(withWindow, base);
  }

  return result;
}

export function filterKey<
  const P extends readonly unknown[],
  A extends Record<string, unknown>,
>(prefix: P, args: A): readonly [...P] | readonly [...P, Partial<A>] {
  const filtered = Object.fromEntries(
    Object.entries(args).filter(([, v]) => v !== undefined),
  );
  return Object.keys(filtered).length > 0
    ? ([...prefix, filtered] as const as any)
    : ([...prefix] as const);
}

export async function unwrapTypedError<T, E>(
  result: Promise<{ status: "ok"; data: T } | { status: "error"; error: E }>,
): Promise<T> {
  const v = await result;
  if (v.status === "error") throw v.error;
  return v.data;
}
